// /* ================= DATA ================= */

// const questions = [

// /* BIOLOGY */
// {
//   subject: "biology",
//   q: "Explain gene regulation in eukaryotes.",
//   a: "Gene regulation in eukaryotes involves transcription factors, chromatin remodeling, and epigenetic modifications that control gene expression in response to environmental and developmental signals."
// },
// {
//   subject: "biology",
//   q: "Describe oxidative phosphorylation.",
//   a: "Oxidative phosphorylation produces ATP through electron transport chains in mitochondria, coupling redox reactions with proton gradients."
// },
// {
//   subject: "biology",
//   q: "Explain immune system specificity.",
//   a: "Immune specificity arises from diverse antigen receptors generated by gene rearrangement, allowing recognition of a vast range of pathogens."
// },

// /* PHYSICS */
// {
//   subject: "physics",
//   q: "Explain the physical meaning of wave-particle duality.",
//   a: "Wave-particle duality describes the fundamental nature of matter and radiation, where particles such as electrons and photons exhibit both wave-like and particle-like properties depending on experimental conditions."
// },
// {
//   subject: "physics",
//   q: "Describe the role of entropy in thermodynamic systems.",
//   a: "Entropy represents the degree of disorder or randomness in a system and determines the direction of spontaneous processes."
// },
// {
//   subject: "physics",
//   q: "Explain band theory in solids.",
//   a: "Band theory explains electrical conductivity in solids by describing allowed and forbidden energy levels for electrons."
// },

// /* CHEMISTRY */
// {
//   subject: "chemistry",
//   q: "Explain molecular orbital theory.",
//   a: "Molecular orbital theory describes chemical bonding by combining atomic orbitals to form molecular orbitals that are delocalized over the molecule."
// },
// {
//   subject: "chemistry",
//   q: "Discuss the concept of chemical potential.",
//   a: "Chemical potential represents the change in free energy with respect to particle number."
// },
// {
//   subject: "chemistry",
//   q: "Describe acid-base equilibria.",
//   a: "Acid-base equilibria involve proton transfer reactions governed by equilibrium constants."
// },

// /* MATHEMATICS */
// {
//   subject: "math",
//   q: "Explain eigenvalues and eigenvectors.",
//   a: "Eigenvalues and eigenvectors characterize linear transformations by identifying invariant directions and scaling factors."
// },
// {
//   subject: "math",
//   q: "Describe Fourier transforms.",
//   a: "Fourier transforms decompose functions into frequency components."
// },
// {
//   subject: "math",
//   q: "Explain convergence of series.",
//   a: "Series convergence determines whether infinite sums approach finite values."
// }

// ];


// /* ================= ELEMENTS ================= */

// const list = document.getElementById("questionList");
// const filterBtns = document.querySelectorAll(".filter-btn");

// /* ================= RENDER ================= */

// function render(subject) {

//   list.innerHTML = "";

//   const filtered =
//     subject === "all"
//       ? questions
//       : questions.filter(q => q.subject === subject);

//   filtered.forEach((item, i) => {

//     const div = document.createElement("div");
//     div.className = "question-item";

//     div.innerHTML = `
//       <div class="question-header">
//         <div class="question-title">
//           ${i + 1}. ${item.q}
//         </div>
//         <div class="arrow">▼</div>
//       </div>

//       <div class="question-body">
//         <div class="video-box">
//           🎥 Video explanation coming soon.
//         </div>
//         <div class="text-box">
//           ${item.a}
//         </div>
//       </div>
//     `;

//     div.querySelector(".question-header")
//       .addEventListener("click", () => {
//         div.classList.toggle("open");
//       });

//     list.appendChild(div);
//   });
// }

// render("all");

// /* ================= FILTER ================= */

// filterBtns.forEach(btn => {

//   btn.addEventListener("click", () => {

//     filterBtns.forEach(b => b.classList.remove("active"));
//     btn.classList.add("active");

//     render(btn.dataset.subject);
//   });

// });
