<?php
$lang = $_SESSION['vendor']['lng'] ?? 'en';
$translations = [
  'en' => [
    'add_customer' => 'Add Customer',
    'bill_id' => 'Bill ID',
    'full_name' => 'Full Name',
    'mobile' => 'Mobile',
    'pick_contact' => 'Pick from contacts',
    'address' => 'Address',
    'submit' => 'Submit',
    'customers_details' => 'Customers Details',
    'search_placeholder' => 'Search name or mobile',
    'refresh' => 'Refresh',
    'no_customers' => 'No customers found.',
    'delete_customer' => 'Delete customer?',
    'delete_warning' => 'This action cannot be undone.',
    'cancel' => 'Cancel',
    'delete' => 'Delete',
    'loading' => 'Loading...',
    'action' => 'Action',
    'customer' => 'Customer',
    'customers' => 'Customers',
    'view' => 'View',
  ],
  'hi' => [
    'add_customer' => 'ग्राहक जोड़ें',
    'bill_id' => 'बिल आईडी',
    'full_name' => 'पूरा नाम',
    'mobile' => 'मोबाइल',
    'pick_contact' => 'संपर्क चुनें',
    'address' => 'पता',
    'submit' => 'जमा करें',
    'customers_details' => 'ग्राहक विवरण',
    'search_placeholder' => 'नाम या मोबाइल खोजें',
    'refresh' => 'रिफ्रेश',
    'no_customers' => 'कोई ग्राहक नहीं मिला।',
    'delete_customer' => 'ग्राहक हटाएं?',
    'delete_warning' => 'यह क्रिया पूर्ववत नहीं की जा सकती।',
    'cancel' => 'रद्द करें',
    'delete' => 'हटाएं',
    'loading' => 'लोड हो रहा है...',
    'action' => 'क्रिया',
    'customer' => 'ग्राहक',
    'customers' => 'ग्राहक',
    'view' => 'देखें',
  ],
  'mr' => [
    'add_customer' => 'ग्राहक जोडा',
    'bill_id' => 'बिल आयडी',
    'full_name' => 'पूर्ण नाव',
    'mobile' => 'मोबाईल',
    'pick_contact' => 'संपर्क निवडा',
    'address' => 'पत्ता',
    'submit' => 'सबमिट करा',
    'customers_details' => 'ग्राहक तपशील',
    'search_placeholder' => 'नाव किंवा मोबाईल शोधा',
    'refresh' => 'रिफ्रेश',
    'no_customers' => 'कोणतेही ग्राहक सापडले नाहीत.',
    'delete_customer' => 'ग्राहक हटवायचा आहे?',
    'delete_warning' => 'ही क्रिया पूर्ववत करता येणार नाही.',
    'cancel' => 'रद्द करा',
    'delete' => 'हटवा',
    'loading' => 'लोड होत आहे...',
    'action' => 'क्रिया',
    'customer' => 'ग्राहक',
    'customers' => 'ग्राहक',
    'view' => 'पहा',
  ],
];
function t($key) {
  global $translations, $lang;
  return $translations[$lang][$key] ?? $translations['en'][$key] ?? $key;
}
?>
